CREATE TABLE Products (maker VARCHAR(200) NOT NULL, model INT UNIQUE NOT NULL, type VARCHAR(100) NOT NULL);
CREATE TABLE PC (model INT NOT NULL PRIMARY KEY, speed FLOAT NOT NULL, ram INT NOT NULL, hd INT NOT NULL, price FLOAT NOT NULL);
CREATE TABLE Laptop (model INT NOT NULL PRIMARY KEY, speed FLOAT NOT NULL, ram INT NOT NULL, hd INT NOT NULL, screen FLOAT NOT NULL, price FLOAT NOT NULL);
CREATE TABLE Printer (model INT NOT NULL PRIMARY KEY, color BIT NOT NULL, type VARCHAR(50) NOT NULL, price FLOAT NOT NULL);
